services:
  dev:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: wavesurfer-peak-extractor-api-dev
    ports:
      - ${DEV_PORT:-3000}:3000
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  prod:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: wavesurfer-peak-extractor-api-prod
    ports:
      - ${PROD_PORT:-3001}:3000
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
